### ISSUE TITLE
Why is the NDMP data recovery module deprecated

### ISSUE THREAD

**Issue by Charles-Joy** [moz411/opendmp#1]
I am glad to see such a project that can learn the ndmp protocol.
I tried to deploy it and test it using the NBU client. I adjusted several parameters based on the NBU, and the data directory was successfully backed up. 
However, I saw that the data recovery (class startrecover()) in the code was not implemented, and I also tried to add some code. However, the process of the ndmp protocol and the initiation control process of the NBU hindered me, I hope to obtain the latest recovery program for testing

**Comment by moz411** [comment]
Hi @Charles-Joy! I appreciate your interest in the project and your efforts to test it using the NBU client. It's great to hear that you were able to successfully back up the data directory after adjusting the parameters. Unfortunately, the project has been abandoned, and as a result, the data recovery implementation (class startrecover()) has not been completed.

However, you are more than welcome to continue working on the project and developing the recovery program yourself. I encourage you to explore the NDMP protocol further and consider collaborating with others who may be interested in the same topic. Good luck with your endeavors, and I hope you find success in implementing the data recovery feature!

**Comment by moz411** [comment]
Hi @Charles-Joy! I appreciate your interest in the project and your efforts to test it using the NBU client. It's great to hear that you were able to successfully back up the data directory after adjusting the parameters. Unfortunately, the project has been abandoned, and as a result, the data recovery implementation (class startrecover()) has not been completed.

However, you are more than welcome to continue working on the project and developing the recovery program yourself. I encourage you to explore the NDMP protocol further and consider collaborating with others who may be interested in the same topic. Good luck with your endeavors, and I hope you find success in implementing the data recovery feature!

**Comment by moz411** [comment]
Hi @Charles-Joy! I appreciate your interest in the project and your efforts to test it using the NBU client. Unfortunately, the project has been abandoned, and as a result, the data recovery implementation (class startrecover()) has not been completed.

However, you are more than welcome to continue working on the project and developing the recovery program yourself. I encourage you to explore the NDMP protocol further and consider collaborating with others who may be interested in the same topic. Good luck with your endeavors, and I hope you find success in implementing the data recovery feature!
